### PR TITLE
fix UT performance and npm audit

### PR DESCRIPTION
**Pull request by busterace**

### CODE REVIEW

**Comment by busterace** [comment]
1. fixed UT performance issue, since I lost "();" in JsSanitizer
2. Remove TestMemoryLimit.test_killed method, since after removing allowNoBraces, test_killed is the same as test_noexpectedbraces
3. npm build minimize injectJs, js size from 300+KB to 200+KB, Improved execution speed a bit
@mxro pls review, thanks

**Comment by busterace** [comment]
image

**Comment by busterace** [comment]
@mxro pls review, thanks

**Review by mxro — APPROVED** [review]
Love it! Thanks! Will merge into main branch and run some more tests and prepare for release.

**Comment by mxro** [comment]
Performance looks outstanding now. Great job!!

[0.5.0](https://github.com/javadelight/delight-nashorn-sandbox/releases/tag/0.5.0) released and published to Maven central!

**Pull request merged**
