### PR TITLE
Use Executor instead of ExecutorService

### PR DESCRIPTION
**Pull request by jlogeart**
The goal of this PR is to loosen the conditions on the `executor` for better interoperability by making it an `Executor` instead of an `ExecutorService`. 

This is a breaking change but it does not have any functional change.

### CODE REVIEW

**Comment by jlogeart** [comment]
@mxro WDYT?

**Comment by mxro** [comment]
Hi Jean, 

Thank you for submitting this pull request. I would be quite hesitant to change the API ... What are the advantages of using Executor instead of ExecutorService? Is there a way to do this in a way that there are no changes to the existing API functions?

Best regards,

Max

**Comment by Frontrider** [comment]
If I understand what it means to do, than I think it would be better if it was an option to use an executor, while keeping the service as well.
The service can be used to get a quick set up, while the executor can give more control when required.

(similar fashion to the way I implemented the bindings.
https://github.com/javadelight/delight-nashorn-sandbox/pull/44)

**Comment by mxro** [comment]
Thanks @jlogeart  and @Frontrider - looks like a useful addition to me! Looking forward to @jlogeart's implementation. Let me know if there is anything I can do to assist.

**Pull request closed without merging**
