### PR TITLE
Refactoring, optimalization, new features

### PR DESCRIPTION
**Pull request by mgolebsk**
Hi, I've rewrite almost all module. Have a look on it.

### CODE REVIEW

**Comment by mxro** [comment]
Thank you for the refactoring. I will check it in detail in a few days since I am travelling at the moment!

**Comment by mgolebsk** [comment]
OK, I will wait

**Comment by mxro** [comment]
Hi! I had a quick look and it all looks great. Just to confirm, there are only very minor changes to the API is that correct?

Would you be fine with being added to the Contributors section in the readme?

**Comment by mgolebsk** [comment]
> Hi! I had a quick look and it all looks great. Just to confirm, there are only very minor changes to the API is that correct?

Yes, it is correct. I have tried not to make unnecessary changes.

> Would you be fine with being added to the Contributors section in the readme?

I would appreciate it.

**Comment by mxro** [comment]
Great, merged the pull request.

Would you like me to use your GitHub handle or your full name. In case of the latter, could you sent to through to me since I couldn't find it on your GitHub profile page.

**Comment by mxro** [comment]
Never mind, I found your full name in the comments!

**Comment by mgolebsk** [comment]
My name is: Marcin Gołębski

**Comment by mxro** [comment]
All done! I've added you to the Contributors section: [commit](https://github.com/javadelight/delight-nashorn-sandbox/commit/1f11e5821f7c7a79f055fb52f4ddc8c3ee1fc8c4).

Also, I've released the new version 0.1.0 to Maven Central which includes all the latest changes. Thank you!

**Pull request merged**
